language: node_js
node_js:
  - '8'
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: pop-movies-teste.surge.sh
  project: ./build/
on:
  branch: master
notifications:
  email:
    recipients:
      - jeovaniaabreu@gmail.com
    on_success: change
    on_failure: always
